<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/templates/Master.master" CodeFile="002.aspx.cs" Inherits="_002" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <blockquote>
        <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>

<p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>

<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
    </blockquote>

    <article>
        <pre><code class="language-csharp">
        int i = 1;
        int x = 0;
        int y = 1;
        int total = 0;
        int newtotal = 0;

        while (total < 4000000)
        {
            total = x + y;

            if (i % 2 == 0)
                y = total;
            else
                x = total;

            i++;

            if (total % 2 == 0)
                newtotal += total;
        }

        int answer = newtotal;
         </code></pre>

    </article>
    <aside>
        <h2>Answer:
            <asp:Literal ID="litAnswer" runat="server"></asp:Literal></h2>
        <h2>Time Taken</h2>
        <asp:Literal ID="litStopWatch" runat="server"></asp:Literal></h2>
    </aside>
</asp:Content>

